# Generated by Django 3.2 on 2025-03-26 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the team', max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Rider's First name", max_length=20, unique=True)),
                ('last_name', models.CharField(help_text="Rider's Surname", max_length=20, unique=True)),
                ('age', models.PositiveIntegerField(help_text="Rider's age in years.")),
                ('age_category', models.CharField(choices=[('U12', 'Under 12'), ('JNR', 'Junior'), ('SNR', 'Senior')], help_text='Age category of the rider', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rider_photos/')),
                ('team', models.ForeignKey(help_text='Team the Rider races for', on_delete=django.db.models.deletion.PROTECT, to='world_cup.team')),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifying_time', models.FloatField()),
                ('main_race_time', models.FloatField(blank=True, null=True)),
                ('race_date', models.DateField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='world_cup.rider')),
            ],
            options={
                'ordering': ['qualifying_time'],
            },
        ),
    ]
